### ISSUE TITLE
help

### ISSUE THREAD

**Issue by silvadenisson** [parlametria/leggoR#713]
Primeiro gostaria de parabenizar a todos pelo projeto.

estou tentando replicar o código do vcs pe estou precisando desse dois arquivos: pressao.csv, interesses.csv, que estão descrito aqui: https://github.com/parlametria/leggoR/blob/master/docs/dados/Sobre.md

fiz um exemplo teste com a proposição PL 4703/2009, que tem os id_camara 424023 e o id_senado 82051

quando executo o código: ./scripts/build_all.R, dar o seguinte erro:

[1] "Processando id 424023 da casa camara"
Error: Problem with `mutate()` column `nome_partido_uf`.
ℹ `nome_partido_uf = paste0(nome, " ", partido, "/", uf)`.
x objeto 'nome' não encontrado
Execução interrompida

o que poderia está acontecendo.. e como solucionar.

grato!

**Comment by hadrizia** [comment]
Olá, @silvadenisson! Obrigada pelo seu contato e pelos elogios!

## Sobre os csvs

- `pressao.csv`: Este csv é gerado pelo [leggoTrends](https://github.com/parlametria/leggoTrends), recomendo que tu dê uma olhada no README para reproduzir os scripts que geram esses dados;
- `interesses.csv`: Para gerar este csv, você precisa inicialmente de uma url com o endereço ou caminho de uma planilha que é input para nossos scripts que geram esse dado. Essa planilha faz um mapeamento do interesse (que chamamos de **painel** no Parlametria) para o local onde a lista de proposições está. Imagino que seu caso seja mais a nível de teste local, então segue um exemplo do formato dessa planilha:

| interesse | url | nome | descricao |
| -- | -- | -- | -- |
| painel | ./inst/ext_data/proposicoes.csv | Proposições | Lista de proposições|

Então você salva este csv em um local, e depois gera tanto o csv de `pls_interesses.csv` quanto o de `interesses.csv`, ambos essenciais para a execução dos demais pipelines:

1. Executando o script que gera pls_interesses.csv:
```{r}
Rscript scripts/interesses/export_pls_leggo.R -u <caminho para a planilha acima> -e <export_filepath>
```
2. Executando o script que gera interesses.csv:
```{r}
Rscript scripts/interesses/export_mapeamento_interesses.R -u <caminho para a planilha acima> -p <pls_interesses_filepath> -e <export_filepath>
```

**Inclusive vou adicionar um README no diretório de interesses com essas informações para as próximas pessoas que vierem a usar o leggoR, muito obrigada!**

## Erro ao executar o build_all.R

Este script é responsável por renderizar nossos relatórios em html no diretório `docs/`, não sei se foi essa a sua intenção, mas é bom te avisar que estes scripts estão ligeiramente desatualizados. Se sua intenção foi rodar todo o pipeline de dados que o leggoR executa, recomendamos dar uma olhada no nosso orquestrador chamado [leggo-geral](https://github.com/parlametria/leggo-geral).

**Comment by silvadenisson** [comment]
Olá!

estou tentando reproduzir essa parte do código do interesse. você poderia fazer uma exemplo com proposição qualquer?


aqui está dando esse erro:
Error: Can't subset columns that don't exist.
x Column `proposicao` doesn't exist.


desde já muito obrigado!

**Comment by hadrizia** [comment]
Aqui está um exemplo do formato da planilha de proposições:

proposicao | id_camara | id_senado | apelido | tema | advocacy_link | keywords | tipo_agenda | prioridade | explicacao_projeto
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
PEC 205/2012 | 553099 |   |   |   |   |   |   |   |  
PEC 32/2020 | 2262083 |   |   |   |   |   |   |   |  
PL 10720/2018 | 2182926 | 131420 |   |   |   |   |   |   |  

Obrigada novamente pelas dúvidas. Vou adicionar o formato desse csv no nosso README. :smile_cat:
