### ISSUE TITLE
Investigar possíveis erros e reportar na issue para futuras correções;

### ISSUE THREAD

**Issue by hadrizia** [parlametria/leggoR#730]

**Comment by hadrizia** [comment]
# Erros e melhorias encontrados:

- Consertados
  - Obtenção da proposição por sigla no Senado. Isso conserta o erro das MPVs terem id só na câmara (o erro ocorria pois a proposição não era retornada pela função). [PR no rcongresso](https://github.com/analytics-ufcg/rcongresso/pull/200);
  - Obtenção das comissões no Senado. [PR no leggoR](https://github.com/parlametria/leggoR/pull/724);
- Futuras correções
  - Problema na atualização do csv de parlamentares no container leggo_data/: a pasta copia arquivos do inst/extdata/parlamentares.csv, mas ao executar os scripts de atualização deste csv, o arquivo de dentro do container não é atualizado.

**Comment by ArthurJahn** [comment]
Problema do arquivo de parlamentares mapeado na issue #737
